version: '3.8'

services:
  pgadmin:
    image: rorylshanks/pgadmin4-auto-login:latest
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - "80:80" # Expose pgAdmin on port 80 of the host
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    restart: always